name: Take screenshot of CBC News front page
on:
  schedule:
    - cron: 30 8 * * *

jobs:
  take_screenshot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run screenshot script
        run: python3 main.py

      - name: Run headline scrape
        run: python3 headlines.py

      - name: Push back to repo
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
